<?php
    $title = 'Execute service';
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<blockquote>
    <p><?php echo $this->service->name ?></p>
    <footer><?php echo $this->service->description ?></footer>
</blockquote>

<h2><small>Parameters</small></h2>

<?php
    $inputParameters = json_decode($this->service->input);
    $link = $this->url('client',
        array(
            'controller' => 'user',
            'action' => 'execute',
            'id' => $this->service->id,
        )
    );
?>

<form action="<?php echo $link ?>" method="post" class="form-horizontal" >
    <?php if(empty($inputParameters)): ?>
        <?php echo 'No input parameters required' ?><br><br>
    <?php else: ?>
        <?php foreach($inputParameters as $key => $inputParam):?>
            <div class="form-group">
                <div class="col-sm-4">
                    <input value="<?php echo $this->parameters[$key] ?>" class="form-control" name="parameters[<?php echo $key ?>]" type="text" placeholder="<?php echo $inputParam ?>">
                </div>
            </div>
        <?php endforeach ?>
    <?php endif ?>
    <input type="submit" class="btn btn-success" value="Execute">
</form>


<?php if($this->error): ?>
    <div class="bg-danger">
        <h3>Error message</h3>
        <div><?php echo $this->error ?></div>
    </div>
<?php elseif($this->results): ?>
    <div class="bg-success">
        <h3>Service Result:</h3>
        <div><h4>
            <?php foreach($this->results as $key =>$result): ?>
                <?php if($key>0) echo ', ' ?>
                <?php echo $result ?>
            <?php endforeach ?>
        </h4></div>
    </div>
<?php endif ?>