<?php

$title = 'Service overview';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if($this->success): ?>
    <table class="table table-striped">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
        <?php foreach($this->services as $item):?>
            <?php
            $link = $this->url('client',
                    array(
                    'controller' => 'user',
                    'action' => 'detail',
                    'id' => $item->id,
                    )
                );
            ?>
            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->name ?></td>
                <td><?php echo $item->description ?></td>
                <td>
                    <a class="btn btn-info" href="<?php echo $link ?>">Details</a>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
<?php else : ?>
    <h1>Error: <?php echo $this->message ?></h1>
<?php endif ?>