<?php

$title = 'Service overview';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table table-striped">
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Description</th>
        <th>Action</th>
    </tr>
    <?php foreach($this->services as $item):?>
        <?php
        $link = $this->url('client',
                array(
                'controller' => 'service',
                'action' => 'detail',
                'id' => $item->id,
                )
            );
        ?>
        <tr>
            <td><?php echo $item->id ?></td>
            <td><?php echo $item->name ?></td>
            <td>--------------</td>
            <td>
                <a class="btn btn-info" href="<?php echo $link ?>">Details</a>
            </td>
        </tr>
    <?php endforeach ?>
</table>