<?php

$title = 'Delete service';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($service->name); ?>' ?
</p>
<?php
$url = $this->url('client', array(
    'controller' => 'admin',
    'action' => 'delete',
    'id'     => $service->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $service->id; ?>" />
        <input class="btn btn-danger" type="submit" name="del" value="Yes" />
        <input class="btn btn-info" type="submit" name="del" value="No" />
    </div>
</form>