<?php

$title = 'Service details';
$this->headTitle($title);
$service = $this->service[0];


if($service->composition == null || empty($service->composition)){
    $isComposition = false;
}else{
    $isComposition = true;
}
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if($this->success): ?>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <td><?php echo $service->id ?></td>
        </tr>
        <tr>
            <th>Name</th>
            <td><?php echo $service->name ?></td>
        </tr>
        <tr>
            <th>Description</th>
            <td><?php echo $service->description ?></td>
        </tr>
        <tr>
            <th>Composition</th>
            <td><span class="glyphicon  <?php echo $isComposition ? 'glyphicon-ok-circle':'glyphicon-remove-circle' ?>"></span></td>
        </tr>
        <?php if($isComposition): ?>
            <tr>
                <th>Composition members</th>
                <td><?php echo implode(', ',json_decode($service->composition)) ?></td>
            </tr>
        <?php endif ?>
        <tr>
            <th>Input</th>
            <?php if($service->input && (!empty($service->input))): ?>
                <td><?php echo implode(', ',json_decode($service->input)) ?></td>
            <?php else: ?>
                <td><pan class="glyphicon glyphicon-remove-circle"></pan></td>
            <?php endif ?>

        </tr>
        <tr>
            <th>Output</th>
            <?php if($service->output && (!empty($service->output))): ?>
                <td><?php echo implode(', ',json_decode($service->output)) ?></td>
            <?php else: ?>
                <td><pan class="glyphicon glyphicon-remove-circle"></pan></td>
            <?php endif ?>        </tr>
        <tr>
            <th>URL</th>
            <td><?php echo $service->url ?></td>
        </tr>

    </table>
<?php else : ?>
    <h1>Error: <?php echo $this->message ?></h1>
<?php endif ?>