<?php

$title = 'Service details';
$this->headTitle($title);
$service = $this->service[0];
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if($this->success): ?>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <td><?php echo $service->id ?></td>
        </tr>
        <tr>
            <th>Name</th>
            <td><?php echo $service->name ?></td>
        </tr>
        <tr>
            <th>Description</th>
            <td><?php echo $service->description ?></td>
        </tr>
        <tr>
            <th>URL</th>
            <td><?php echo $service->url ?></td>
        </tr>
    </table>
<?php else : ?>
    <h1>Error: <?php echo $this->message ?></h1>
<?php endif ?>