<?php
$title = 'Edit service';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('client', array('controller' => 'admin', 'action' => 'edit', 'id' => $form->get('id')->getValue())));
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')); ?>

    <div class="form-group">
        <label  class="control-label col-sm-2"><?php echo $this->translate('Name'); ?></label>
        <div class="col-sm-10">
            <?php echo $this->formRow($form->get('name')); ?>
        </div>
    </div>


    <div class="form-group">
        <label  class="control-label col-sm-2"><?php echo $this->translate('Description'); ?></label>
        <div class="col-sm-10">
            <?php echo $this->formRow($form->get('description')); ?>
        </div>
    </div>


    <div class="form-group">
        <label  class="control-label col-sm-2"><?php echo $this->translate('Url'); ?></label>
        <div class="col-sm-10">
            <?php echo $this->formRow($form->get('url')); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>

<?php echo $this->form()->closeTag(); ?>

<?php if($this->errorMessage): ?>
    <div class="bg-danger">
        <h3>Error message</h3>
            <?php foreach($this->errorMessage as $param => $error): ?>

                <div><?php echo '<b>Parameter:</b> ' .$param  ?></div>
                <?php foreach($error as $type => $description): ?>
                    <div style="margin-left: 20px;"><?php echo '<b>'.$type.':</b> ' .$description  ?></div>

                <?php endforeach ?>

            <?php endforeach ?>
    </div>
<?php endif ?>