<?php

$title = 'Service overview';
$this->headTitle($title);

$addLink = $this->url('client',
    array(
        'controller' => 'admin',
        'action' => 'add',
    )
);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p><a class="btn btn-primary" href="<?php echo $addLink; ?>">Add new service</a></p>

<?php if($this->success): ?>


    <table class="table table-striped">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
        <?php foreach($this->services as $item):?>
            <?php
            $link = $this->url('client',
                    array(
                    'controller' => 'admin',
                    'action' => 'detail',
                    'id' => $item->id,
                    )
                );
            $editLink = $this->url('client',
                array(
                    'controller' => 'admin',
                    'action' => 'edit',
                    'id' => $item->id,
                )
            );
            $deleteLink = $this->url('client',
                array(
                    'controller' => 'admin',
                    'action' => 'delete',
                    'id' => $item->id,
                )
            );
            ?>
            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->name ?></td>
                <td><?php echo $item->description ?></td>
                <td>
                    <a class="btn btn-info" href="<?php echo $link ?>">Details</a>
                    <a class="btn btn-warning" href="<?php echo $editLink ?>">Edit</a>
                    <a class="btn btn-danger" href="<?php echo $deleteLink ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
<?php else : ?>
    <h1>Error: <?php echo $this->message ?></h1>
<?php endif ?>