<?php

$title = 'Service overview';
$this->headTitle($title);

$addLink = $this->url('client',
    array(
        'controller' => 'admin',
        'action' => 'add',
    )
);

$filterLink = $this->url('client',
    array(
        'controller' => 'admin',
        'action' => 'index',
    )
);

?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p><a class="btn btn-primary" href="<?php echo $addLink; ?>">Add new service</a></p>

<p>
    <br />
    <form class="form-inline" method="get" action="<?php echo $filterLink ?>">
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" id="description" name="description" value="<?php echo $this->description ?>">
        </div>
        <div class="form-group">
            <label for="category">Category</label>
            <input type="text" class="form-control" id="category" name="category" value="<?php echo $this->category ?>">
        </div>
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-filter" aria-hidden="true"></span>Filter
        </button>    </form>
</p>
<br />

<?php if($this->success): ?>


    <table class="table table-striped">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Description</th>
            <th>Categories</th>
            <th>Action</th>
        </tr>
        <?php foreach($this->services as $item):?>
            <?php
            $link = $this->url('client',
                    array(
                    'controller' => 'admin',
                    'action' => 'detail',
                    'id' => $item->id,
                    )
                );
            $editLink = $this->url('client',
                array(
                    'controller' => 'admin',
                    'action' => 'edit',
                    'id' => $item->id,
                )
            );
            $executeLink = $this->url('client',
                array(
                    'controller' => 'user',
                    'action' => 'execute',
                    'id' => $item->id,
                )
            );
            $deleteLink = $this->url('client',
                array(
                    'controller' => 'admin',
                    'action' => 'delete',
                    'id' => $item->id,
                )
            );
            ?>
            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->name ?></td>
                <td><?php echo $item->description ?></td>

                <td>
                    <?php if($item->categories && (!empty($item->categories))): ?>
                        <?php echo implode(', ',json_decode($item->categories)) ?>
                    <?php endif ?>
                </td>

                <td>
                    <a class="btn btn-info" href="<?php echo $link ?>">Details</a>
                    <a class="btn btn-warning" href="<?php echo $editLink ?>">Edit</a>
                    <a class="btn btn-danger" href="<?php echo $deleteLink ?>">Delete</a>
                    <a class="btn btn-success" href="<?php echo $executeLink ?>">Execute</a>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
<?php else : ?>
    <h1>Error: <?php echo $this->message ?></h1>
<?php endif ?>